package yaboichips.modname.lists;

import net.minecraft.block.Block;
import net.minecraft.block.DoorBlock;
import net.minecraft.block.SlabBlock;

public class BlockList {

    public static Block marble;
    public static Block black_concrete_stair;
    public static Block white_concrete_stair;
    public static Block orange_concrete_stair;
    public static Block cyan_concrete_stair;
    public static Block blue_concrete_stair;
    public static Block light_blue_concrete_stair;
    public static Block lime_concrete_stair;
    public static Block red_concrete_stair;
    public static Block green_concrete_stair;
    public static Block yellow_concrete_stair;
    public static Block gray_concrete_stair;
    public static Block purple_concrete_stair;
    public static Block brown_concrete_stair;
    public static Block pink_concrete_stair;
    public static Block light_gray_concrete_stair;
    public static Block magenta_concrete_stair;
    public static Block white_neon_block;
    public static Block red_neon_block;
    public static Block perfectly_clear_glass;
    public static Block blue_neon_block;
    public static Block pink_neon_block;
    public static Block yellow_neon_block;
    public static Block light_blue_neon_block;
    public static Block purple_neon_block;
    public static Block green_neon_block;
    public static Block funny_neon_block;
    public static Block orange_neon_block;
    public static Block asphalt;
    public static Block flannel;
    public static Block red_tinted_glass;
    public static Block yellow_tinted_glass;
    public static Block tinted_glass_block;
    public static Block green_tinted_glass;
    public static Block lattice;
    public static Block blue_tinted_glass;
    public static Block steel_block;
    public static Block white_concrete_slab;
    public static Block cinder_bricks;
    public static Block hardwood_planks;
    public static Block shoji;
    public static DoorBlock shoji_door;
    public static Block cherry_leaves;
    public static Block hardwood_log;
    public static SlabBlock hardwood_slab;
    public static Block hardwood_sapling;
    public static Block hardwood_stairs;
    public static Block rubber_block;
    public static Block holy_hand_grenade;
    public static Block green_kyber_ore;
    public static Block blue_kyber_ore;
    public static Block purple_kyber_ore;
    public static Block marthas_drumstick_cake;
}